# Docker compose configuration to run project locally
version: "3"

services:
  redis:
    image: redis:5
  rabbitmq:
    image: rabbitmq:3
  web:
    build:
      context: .
      args:
        - REQUIREMENT_PATH=requirements/local.txt
    image: chat_app_local_image
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .envs/local.env
    volumes:
      - ./src:/src
    depends_on:
      - redis
      - rabbitmq
  celery_worker:
    image: chat_app_local_image
    working_dir: /src/
    entrypoint: ["celery", "-A", "chatApp", "worker", "-Q", "celery", "-l", "INFO"]
    env_file:
      - .envs/local.env
    volumes:
      - ./src:/src
    depends_on:
      - web
      - rabbitmq

volumes:
  src:
